### ISSUE TITLE
some question

### ISSUE THREAD

**Issue by zkjkak** [maxwell0027/PEFAT#1]
Thank you for your outstanding contribution in the field of semi-supervision. My research direction is also semi-supervision. I don't know where to download your paper. Can you give me a download link if it's convenient.

**Comment by maxwell0027** [comment]
Thanks for your attention, the paper is available at https://openaccess.thecvf.com/content/CVPR2023/papers/Zeng_PEFAT_Boosting_Semi-Supervised_Medical_Image_Classification_via_Pseudo-Loss_Estimation_and_CVPR_2023_paper.pdf
