### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by wangnaihao** [maxwell0027/PEFAT#2]
Hi!Thanks for your excellent work!I find a bug in train.py in line 508,the correct should be feat_u2 not feat_u1.

**Comment by maxwell0027** [comment]
Thanks for pointing out this mistake!

**Comment by wangnaihao** [comment]
hi！I have another question now,did you forget apply normalize_l2 to trust_img's grad during each iter of args.K

**Comment by maxwell0027** [comment]
Sorry for the late reply! It has little impact to apply normalize_l2 to trust_img's grad.
