### ISSUE TITLE
Regarding the unresolved reference "models" in the load_model function.

### ISSUE THREAD

**Issue by Betty-J** [maxwell0027/PEFAT#3]
Thank you for sharing your work. I noticed an Unresolved reference 'models' in ./code/utils/util.py while reading the code. The screenshot is attached below. I would like to know the reason behind this issue. Is it related to the versions of some environment packages?
<img width="709" alt="截屏2023-08-01 17 02 24" src="https://github.com/maxwell0027/PEFAT/assets/23076443/bf08649c-5ad5-4d60-a46f-60a10dbb6183">

**Comment by maxwell0027** [comment]
Sorry for the late reply! You can simply add the commond "import torchvision.models as models".

**Comment by Betty-J** [comment]
> Sorry for the late reply! You can simply add the commond "import torchvision.models as models".

Thanks for reply.
